### PR TITLE
Add Makefile for armcc

### PR DESCRIPTION
**Pull request by howard0su**
Add a makefile to run armcc on Linux to build the firmware

### CODE REVIEW

**Comment by ghostface** [comment]
Ok took me a bit of fiddling to get this installed on linux.

To help others:

Download linux version of the arm compiler 5 here: https://developer.arm.com/products/software-development-tools/compilers/arm-compiler/downloads/version-5

Download Keil MDK Lite v5 for windows here: http://www2.keil.com/mdk5/editions/lite/
Install using wine or extract it somehow (i installed it via wine).

Copy elmap files from C:/Keil_v5/ARM/sw/mappings to /usr/local/ARM_Compiler_5.06u6/sw/mappings/

Make file should now run. If your ARM compiler install is not in your linux path either add it permanently or add it temporarily by executing:

`export PATH=/usr/local/ARM_Compiler_5.06u6/bin/:"$PATH" && make`

I was able to compile without issues on linux then.

Interestingly the compiled hey is a bit smaller compared to a hex compiled via the windows binaries and wine, possibly due to wine? Somebody should maybe check on a native installation.

> 43908 Mar  6 11:14 armcc/silverware.hex    <- linux compile
> 44900 Mar  6 11:21 BWhoop.hex                 <- windows compile

Thank you @howard0su !

**Comment by howard0su** [comment]
hex file size is not necessary reflecting the firmware size. It is possible the link order of the object files cause the difference of the firmware.

**Comment by ghostface** [comment]
@howard0su gotcha

For reference this is the makefile is used under windows/wine

```
@echo off

REM * Batch makefile for silverware
REM * Place in the project root folder (next to Silverware), make sure you also have keil_v5 tools there.
REM * Usage: ./make.bat
REM * More info:
REM *    http://www.keil.com/support/man/docs/armcc/armcc_chr1359124898004.htm
REM *    http://www.keil.com/support/man/docs/armlink/armlink_pge1362075395210.htm
REM *    http://www.keil.com/support/man/docs/armasm/armasm_dom1361289815333.htm
REM * Created by Phobos

echo Building SilverWare...

SET OBJDIR=.\silverware\objects
SET KEILDIR=C:\Keil_v5\ARM\ARMCC\bin

SET SRC=.\silverware\src .\Utilities .\Libraries\STM32F0xx_StdPeriph_Driver\src
SET INC=-I .\silverware\src -I .\Libraries\CMSIS\Device\ST\STM32F0xx\Include -I .\Libraries\CMSIS\Include -I .\Utilities -I .\Libraries\STM32F0xx_StdPeriph_Driver\inc
SET STARTUP=.\Libraries\CMSIS\Device\ST\STM32F0xx\Source\Templates\arm\startup_stm32f031.s

SET CPU=--cpu Cortex-M0
SET OPT=-c %CPU% -D__EVAL -D__MICROLIB -g -O2 --apcs=interwork --split_sections -D__UVISION_VERSION="524" -DUSE_STDPERIPH_DRIVER -DSTM32F031 --fpmode=fast
SET LST=%CPU% --pd "__EVAL SETA 1" -g --apcs=interwork --pd "__MICROLIB SETA 1" --pd "__UVISION_VERSION SETA 524" --xref
SET LINK=%CPU% --library_type=microlib --ro-base 0x08000000 --entry 0x08000000 --rw-base 0x20000000 --entry Reset_Handler --first __Vectors --strict --info summarysizes

SET ARMCC5_ASMOPT=--diag_suppress=9931
SET ARMCC5_CCOPT=--diag_suppress=9931
SET ARMCC5_LINKOPT=--diag_suppress=9931
SET CPU_TYPE=STM32F030F4
SET CPU_VENDOR=STMicroelectronics
SET UV2_TARGET=BWhoop
SET CPU_CLOCK=0x00B71B00
SET ARM_TOOL_VARIANT=mdk_lite
SET ARM_PRODUCT_PATH=C:\Keil_v5\ARM\sw\mappings


if not exist %OBJDIR% mkdir %OBJDIR%

for %%i in (%SRC%) do (
  for /f "usebackq TOKENS=*" %%j in (`dir /b %%i\*.c 2^>nul`) do %KEILDIR%\armcc --c99 %OPT% %INC% -o %OBJDIR%\%%~nj.o %%i\%%~nxj
  for /f "usebackq TOKENS=*" %%k in (`dir /b %%i\*.cpp 2^>nul`) do %KEILDIR%\armcc --cpp %OPT% %INC% -o %OBJDIR%\%%~nk.o %%i\%%~nxk
)
%KEILDIR%\armasm %LST% -o %OBJDIR%\startup_stm32f031.o %STARTUP%

setlocal ENABLEDELAYEDEXPANSION
set objList=
for /f "usebackq TOKENS=*" %%a in (`dir /b %OBJDIR%\*.o 2^>nul`) do set objList=!objList! %OBJDIR%\%%a

%KEILDIR%\armlink %LINK% %objList% -o %OBJDIR%\%UV2_TARGET%.axf
%KEILDIR%\fromelf %OBJDIR%\%UV2_TARGET%.axf --i32combined --output .\%UV2_TARGET%.hex

rmdir /s /q %OBJDIR%

pause

```

**Comment by JamesKingdon** [comment]
Thanks @howard0su @ghostface - this was perfect timing, I was just trying to figure this out today! One thing that might be worth mentioning for people who are moving from the gcc instructions, is the difference between the binary output from the gcc steps vs the the .hex produced by the above. I had to modify the flash command I was using to 
`openocd -f /usr/share/openocd/scripts/interface/stlink-v2.cfg -f /usr/share/openocd/scripts/target/stm32f0x.cfg -c init -c "reset halt" -c "flash write_image erase silverware.hex" -c "reset run" -c shutdown`

**Pull request merged**
