### PR TITLE
Implemented betaflight rates

### PR DESCRIPTION
**Pull request by phobos-**
I copied this piece of code from betaflight a long time ago, it is working well.
I think it is a really good addition, as currently silverware is lacking the super expo feel. It is quite different than standard expo.

Small how-to:

1. Uncomment BETAFLIGHT_RATES define in config.h
2. Set your rates/super expo + angle/acro expo.
3. Save and flash your quad.

To disable simply comment out BETAFLIGHT_RATES in config.h

### CODE REVIEW

**Comment by phobos-** [comment]
@xfOLx 
I'd love to see some feedback from you :)

**Comment by Tarkusx** [comment]
Gonna give a try and see how it fly ! Thank you for sharing this code

**Comment by NotFastEnuf** [comment]
Sorry this sat so long.  Excellent work

**Comment by Tarkusx** [comment]
Well , i did try again tonight and i keep coming back to Default NFE ! Feel good just like BF , probably good for people who dont want to lost track or their muscle memory from Betaflight rates/srates

**Pull request merged**
