### PR TITLE
Hmb silverware

### PR DESCRIPTION
**Pull request by yangyeah**
add baro and altitude hold
add beesign protocol (It's used on VTX MARK2 witch support vtx and osd, single wire)
update sbus and dsm to support beesign
add a menu like betaflight
add a button , double click it can go in RX menu
add stick command

### CODE REVIEW

**Comment by NotFastEnuf** [comment]
Excellent work, I am enjoying reviewing your changes.  There is quite a bit of work to do in order to bring in the target and maintain the NFE fork's compatibility with other targets and products but I am already getting a good idea on how to make it happen.  Where shall we come together on changes?  Are you comfortable with me pushing changes directly to the czchc/NFE_Silverware HMB_Silverware branch so that this PR updates with the changes we make, or would you like to keep that one clean and have me open another branch on my repo to tweak it?

Again thank you for your work and contribution to the project.

**Comment by yangyeah** [comment]
We think you can open another branch, There are some differences in hardware. likes baro and button. and we use hardware i2c. And other FC don't have enough flash and ram to support beesign.

**Comment by NotFastEnuf** [comment]
Yes, and that's just the beginning of the list.  There are two FC models supported by NFE which require software i2c for their gyros due to layout without resistor on the clock line, differences in rssi channel number, some dsm radios that can not scale to 147% to reach full throws standardized by betaflight and need the adjustable scalefactor, the concept of linking different default user settings selections to different manufacturer products,  and others things too.  However, there are simple solutions to all these things.  All the f0 support 32kb though, even the ones that spec at 16kb.  My defaults have always saved accelerometer calibration and real-time user variables selected through stick gestures to the last block of memory up against the edge of the 32kb mark.

Ok.  I will open another branch and address the compatibility issues there before merging.  I just wanted to check first as it seems like I had write permission to your branch within the GitHub system, but did not know if it was actually your intention for me to push changes there or not.  Thank you for the clarification.

**Comment by czchc** [comment]
Hi, it is okay you push commits there, and i just added you as collaborator. :)

**Comment by yangyeah** [comment]
For sbus， there have not enough ram for system. and the menu can't expand. when I make the hummingbird sbus target, it's used  4080 Byte ram. so we should used STM32 witch at least 4K ram.

**Comment by NotFastEnuf** [comment]
@czchc, thank you for the collaborator invite.  I am not against the idea of working in a branch off the main repo.  It could have it's benefits, and attract others in the development community to participate.  I think this is good for us to discuss our plans for workflow management.  Maybe we work in your branch for a bit, then once it is closer move it over to a branch off of NFE where others can test and participate.  Tell me what you think

**Comment by czchc** [comment]
Agree, we should move back to NFE repos as we forked here and did something based on your work.

**Pull request closed without merging**
